server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity_service
    username: root
    password: Chiduy171203

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true

jwt:
  signerKey: "eDvTlohzG6dHiJU9GdHzVGBq3T9b/UaLG9yqif0EuejdhEFOCuV4YHBIQjSNLG5Z"
  valid-duration: 3600 #in second
  refreshable-duration: 360000 #in second

#      ddl-auto: create
#      ddl-auto: update
#      ddl-auto: create-drop
